export const TASK_ADDED = 'TASK_ADDED'
export const TASK_STATUS_UPDATE = 'TASK_STATUS_UPDATE'
export const TASK_COUNT_UPDATE = 'TASK_COUNT_UPDATE'
export const UPDATE_TASK_COMPLETE_STATUS = 'UPDATE_TASK_COMPLETE_STATUS'